Feat/remove composer json
MacPaw/ExtendedMockHttpClient pull request #11
Opened 2020-12-18 19:27 UTC by Yozhef

2020-12-20 13:17 UTC, alekseytupichenkov requested changes

2020-12-20 13:17 UTC, alekseytupichenkov commented on .gitignore
> +composer.lock
Это прям плохой вариант, у нас зависимости будут обновлятся неконтролируемо

2020-12-20 14:01 UTC, Yozhef commented on .gitignore
> +composer.lock
```
        "php": "^7.1",
        "symfony/http-client": "^4.4 || ^5.0",
        "symfony/cache": "^4.4 || ^5.0" 
        
     ```
     
   По факту в тебе все закріплене в композері - тому все буде окей. 
   А те що буде автоматом пач підключатись навпаки правельно. 
   Бо наприклад виходить фікс чогось а тобі треба зайти в кожну лібу і обновити композар щоб сказачати мінорний пач =(

2020-12-21 09:21 UTC, Yozhef commented on .gitignore
> +composer.lock
Його в коміті нема - бо в мастері його теж нема =) 
Просто без гіт ігнору не комітили =)

2020-12-21 09:28 UTC, merged